# Generated by Django 5.1.5 on 2025-02-06 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.IntegerField(primary_key=True, serialize=False)),
                ('abierta_caja', models.IntegerField()),
                ('fecha_hs_aper_caja', models.DateTimeField()),
                ('fecha_hs_cier_caja', models.DateTimeField()),
                ('monto_inicial_caja', models.FloatField()),
                ('total_ingresos_caja', models.FloatField()),
                ('total_egresos_caja', models.FloatField()),
                ('saldo_caja', models.FloatField()),
                ('id_empl', models.ForeignKey(db_column='id_empl', on_delete=django.db.models.deletion.DO_NOTHING, to='Empleados.empleados')),
            ],
        ),
    ]
