# Generated by Django 5.1.5 on 2025-02-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajas', '0002_alter_caja_abierta_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo_caja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_egresos_caja',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_ingresos_caja',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
