# Generated by Django 5.1.5 on 2025-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='hora_venta',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
