# Generated by Django 5.1.5 on 2025-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Ventas', '0002_alter_ventas_fecha_venta_alter_ventas_hora_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_det_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod_venta', models.IntegerField()),
                ('subtotal_det', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('id_prod', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.ventas')),
            ],
        ),
    ]
