# Generated by Django 5.1.5 on 2025-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePed',
            fields=[
                ('id_det_ped', models.IntegerField(primary_key=True, serialize=False)),
                ('precio_uni_ped', models.FloatField()),
                ('cantidad_ped', models.FloatField()),
                ('sub_total_ped', models.FloatField()),
                ('total_ped', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('generado_ped', models.IntegerField()),
                ('fecha_gen_ped', models.DateField()),
                ('hora_gen_ped', models.TimeField()),
                ('proceso_ped', models.IntegerField()),
                ('fecha_pro_ped', models.DateField(blank=True, null=True)),
                ('hora_pro_ped', models.TimeField(blank=True, null=True)),
                ('listo_ped', models.IntegerField()),
                ('fecha_lis_ped', models.DateField(blank=True, null=True)),
                ('hora_lis_ped', models.TimeField(blank=True, null=True)),
                ('entregado_ped', models.IntegerField()),
                ('fecha_ent_ped', models.DateField(blank=True, null=True)),
                ('hora_ent_ped', models.TimeField(blank=True, null=True)),
                ('pagado_ped', models.IntegerField()),
                ('fecha_pago_ped', models.TimeField(blank=True, null=True)),
                ('tipo_pago_ped', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
