# Generated by Django 5.1.5 on 2025-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cajas', '0002_alter_caja_abierta_caja_and_more'),
        ('Empleados', '0001_initial'),
        ('Mesas', '0001_initial'),
        ('Pedidos', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Ventas', '0003_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleped',
            name='id_prod',
            field=models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_caja',
            field=models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='Cajas.caja'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_empl',
            field=models.ForeignKey(db_column='id_empl', on_delete=django.db.models.deletion.DO_NOTHING, to='Empleados.empleados'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_mesa',
            field=models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.DO_NOTHING, to='Mesas.mesas'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.ventas'),
        ),
        migrations.AddField(
            model_name='detalleped',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='Pedidos.pedidos'),
        ),
    ]
