# Generated by Django 5.1.5 on 2025-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
