# Generated by Django 5.1.5 on 2025-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empl', models.IntegerField(primary_key=True, serialize=False)),
                ('dni_empl', models.IntegerField()),
                ('nombre_empl', models.CharField(max_length=50)),
                ('apellido_empl', models.CharField(max_length=50)),
                ('domicilio_empl', models.CharField(max_length=50)),
                ('telefono_empl', models.IntegerField(blank=True, null=True)),
                ('correo_empl', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
