# Generated by Django 5.1.5 on 2025-02-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
