# Generated by Django 5.1.5 on 2025-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_productos_id_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre_prod',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_prod',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_actual_prod',
            field=models.IntegerField(verbose_name='Stock actual'),
        ),
    ]
