# Generated by Django 5.1.5 on 2025-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=100)),
                ('apellido_cli', models.CharField(max_length=100)),
                ('cuit_cli', models.IntegerField()),
                ('tel_cli', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
