# Generated by Django 5.1.5 on 2025-02-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.IntegerField(primary_key=True, serialize=False)),
                ('num_mesa', models.IntegerField()),
                ('disponible_mesa', models.IntegerField()),
            ],
        ),
    ]
