# Generated by Django 5.1.5 on 2025-02-17 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cajas', '0002_alter_caja_abierta_caja_and_more'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_comp', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_comp', models.DateTimeField()),
                ('monto_comp', models.FloatField()),
                ('nro_comp', models.IntegerField()),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='Cajas.caja')),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.DO_NOTHING, to='Proveedores.proveedores')),
            ],
        ),
    ]
