# Generated by Django 5.1.5 on 2025-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha_hora_comp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
