# Generated by Django 5.1.5 on 2025-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_compras_fecha_hora_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id_det_comp', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_prod_comp', models.IntegerField()),
                ('precio_uni_prod', models.FloatField()),
                ('sub_total_comp', models.FloatField()),
                ('total_comp', models.FloatField()),
                ('id_comp', models.ForeignKey(db_column='id_comp', on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.compras')),
            ],
        ),
    ]
