# Generated by Django 5.1.5 on 2025-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_detallecompras'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompras',
            name='id_prod',
            field=models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.DO_NOTHING, to='Productos.productos'),
        ),
    ]
