# Generated by Django 5.1.5 on 2025-02-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_prov', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=50)),
                ('tipo_prov', models.CharField(max_length=50)),
                ('telefono_prov', models.IntegerField(blank=True, null=True)),
                ('correo_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_prov', models.CharField(max_length=50)),
            ],
        ),
    ]
